name: 'Run Jenkins Job and get build result'
description: 'Triggers Jenkins Job and get build result'
author: 'Toptal'
inputs:
  jenkins_url:
    required: true
    description: 'Jenkins domain URL'
  jenkins_user:
    required: true
    description: 'Jenkins username'
  jenkins_token:
    required: true
    description: 'Jenkins API token that belongs to jenkins_user'
  job_name:
    required: true
    description: 'Jenkins job to triggered and follow up'
  iap_token:
    description: 'Token to authenticate to Identity Aware Proxy (IAP)'
    required: true
  job_params:
    description: 'Jenkins build job parameters, encoded in JSON'
    required: false
  job_timeout:
    description: 'Jenkins job timeout period. Default 30 seconds'
    required: false
    default: '30'
  proxy:
    required: false
    description: 'Proxy url, which includes username and password'
  async:
    description: 'Set to true if you want to just trigger the job without waiting for it to finish'
    required: false
    default: 'false'
outputs:
  jenkins_job_url:
    description: 'URL to the job details'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'green'
